# Tests on Localhost: 3000
GET http://localhost:3000/contacts 

###

GET http://localhost:3000/contacts/6276d5a48464683b8550117e

###

POST http://localhost:3000/newContact/
Accept: application/json,
content-type: application/json

{
    "firstName": "Kevin",
    "lastName": "Char",
    "email": "k.char@email.com",
    "favoriteColor": "Black",
    "birthday": "1979-04-12"
}
###

PUT http://localhost:3000/editContact/6276d5a48464683b8550117e
Accept: application/json,
content-type: application/json

{
    "firstName": "Tyson",
    "lastName": "Jacksons",
    "favoriteColor": "Pink"
}
###

DELETE http://localhost:3000/deleteContact/6276d5a48464683b8550117e

###


# Tests on Production site
GET https://cse341-muto.herokuapp.com/contacts

###

GET https://cse341-muto.herokuapp.com/contacts/6276d5cad4bb8c11767e76cb

###

POST https://cse341-muto.herokuapp.com/newContact
Accept: application/json,
content-type: application/json

{
    "firstName": "Masami",
    "lastName": "Ito",
    "email": "m.ito@email.com",
    "favoriteColor": "Purple",
    "birthday": "1986-08-12"
}
###

PUT http://cse341-muto.herokuapp.com/editContact/6276d5cad4bb8c11767e76cb
Accept: application/json,
content-type: application/json

{
    "lastName": "Levin",
    "favoriteColor": "Gold"
}
###

DELETE http://cse341-muto.herokuapp.com/deleteContact/6276d5cad4bb8c11767e76cb

